# Generated by Django 6.1.1 on 2026-09-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('win', 'Win'), ('lose', 'Lose')], db_index=True, default='active', max_length=10),
        ),
    ]
