# Generated by Django 6.1.1 on 2026-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_alter_vote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('win', 'Win'), ('lose', 'Lose'), ('void', 'Void')], db_index=True, default='active', max_length=10),
        ),
    ]
