# Generated by Django 6.1.1 on 2026-09-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_start_time_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
