# Generated by Django 6.1.1 on 2026-09-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_external_id_team_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
