# Generated by Django 6.1.1 on 2026-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_team_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished'), ('canceled', 'Canceled')], db_index=True, default='upcoming', max_length=10),
        ),
    ]
