# Generated by Django 6.1.1 on 2026-09-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_cointransaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='type',
            field=models.CharField(choices=[('bet_stake', 'Bet stake'), ('bet_win', 'Bet win'), ('bet_lose', 'Bet lose'), ('bet_refund', 'Bet refund'), ('ad_reward', 'Ad reward'), ('signup_bonus', 'Signup bonus'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
